export const bannerData = {
  about: {
    background: require("../assets/images/aboutusbanner.jpg"),
    title: "About Us",
    crumb: "About Us",
    watermark: "Excelfy Technologies",
  },
  faq: {
    background: "images/banner/bnr-4.jpg",
    title: "Faq Page",
    crumb: "Faq Page",
    watermark: "Excelfy Technologies",
  },
  gallery: {
    background: "images/banner/bnr-2.jpg",
    title: "Gallery Page",
    crumb: "Gallery Page",
    watermark: "Excelfy Technologies",
  },
  icons: {
    background: "images/banner/bnr-4.jpg",
    title: "Icons",
    crumb: "icon-font",
    watermark: "Excelfy Technologies",
  },
  testimonials: {
    background: "images/banner/bnr-3.jpg",
    title: "Testimonials",
    crumb: "Testimonials",
    watermark: "Excelfy Technologies",
  },
  whychooseus: {
    background: "images/banner/bnr-8.jpg",
    title: "Why Choose us",
    crumb: "Why Choose us",
    watermark: "Excelfy Technologies",
  },
  pricing: {
    background: "images/banner/bnr-7.jpg",
    title: "Price Table",
    crumb: "Price Table",
    watermark: "Excelfy Technologies",
  },
  team: {
    background: "images/banner/bnr-2.jpg",
    title: "Team Member",
    crumb: "Team Member",
    watermark: "Excelfy Technologies",
  },
  mission: {
    background: "images/banner/bnr-7.jpg",
    title: "Mission & Vision",
    crumb: "Mission & Vision",
    watermark: "Excelfy Technologies",
  },
  services: {
    background: require("../assets/images/ourservicesbanner.webp"),
    title: "Our Services",
    crumb: "Our Services",
    watermark: "Excelfy Technologies",
  },
  portfolio1: {
    background: "images/banner/bnr-4.jpg",
    title: "Portfolio Page",
    crumb: "Portfolio",
    watermark: "Excelfy Technologies",
  },
  portfolio2: {
    background: "images/banner/bnr-5.jpg",
    title: "Portfolio-2 Page",
    crumb: "Portfolio-2 Page",
    watermark: "Excelfy Technologies",
  },
  portfoliodetail: {
    background: "images/banner/bnr-7.jpg",
    title: "Portfolio Detail",
    crumb: "Portfolio Detail",
    watermark: "Excelfy Technologies",
  },
  bloggrid: {
    background: "images/banner/bnr-1.jpg",
    title: "Blog Page",
    crumb: "Blog Page",
    watermark: "Excelfy Technologies",
  },
  bloglistsidebar: {
    background: "images/banner/bnr-8.jpg",
    title: "Blog Archive",
    crumb: "Blog Single Grid",
    watermark: "Excelfy Technologies",
  },
  blogdetail: {
    background: "images/banner/bnr-1.jpg",
    title: "Blog detail",
    crumb: "Blog detail",
    watermark: "Excelfy Technologies",
  },
  blogdetailsidebar: {
    background: "images/banner/bnr-10.jpg",
    title: "Blog detail",
    crumb: "Blog detail",
    watermark: "Excelfy Technologies",
  },
  contact: {
    background: require("../assets/images/contactbanner.jpg"),
    title: "Contact Us",
    crumb: "Contact Us",
    watermark: "Excelfy Technologies",
  },
};
